#define P1LED_ON HAL_GPIO_WritePin(LED1_GPIO_Port,LED1_Pin, RESET)
#define P1LED_OFF HAL_GPIO_WritePin(LED1_GPIO_Port,LED1_Pin, SET)
#define P2LED_ON HAL_GPIO_WritePin(LED2_GPIO_Port,LED2_Pin, RESET)
#define P2LED_OFF HAL_GPIO_WritePin(LED2_GPIO_Port,LED2_Pin, SET)