#define BLUELED_ON HAL_GPIO_WritePin(LED1_GPIO_Port,LED1_Pin, RESET)
#define BLUELED_OFF HAL_GPIO_WritePin(LED1_GPIO_Port,LED1_Pin, SET)
#define REDLED_ON HAL_GPIO_WritePin(LED2_GPIO_Port,LED2_Pin, RESET)
#define REDLED_OFF HAL_GPIO_WritePin(LED2_GPIO_Port,LED2_Pin, SET)
